# Generated by Django 4.2.25 on 2025-10-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_video_thumbnail_image_video_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series_posters/')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['series', 'season_number', 'episode_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='season_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, help_text="The series this video belongs to, if it's an episode.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='streaming.series'),
        ),
    ]
