# Generated by Django 4.2.25 on 2025-10-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_series_alter_video_options_video_episode_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'season_number', 'episode_number'), name='unique_episode_in_series'),
        ),
    ]
